Added a notification that alerts the player when a certain amount of time has elapsed since the last distraction
sololegends/runelite-varlamore-house-thieving pull request #7
Opened 2024-07-09 23:04 UTC by coupe-1

Also, removed redundant "Notify On" strings from the notification options. I think it looks cleaner.

2024-07-09 23:57 UTC, sololegends commented
I'm not sure I see the general point of this addition. There wouldn't be anything actionable after the distraction timers counts up to a specified number. The actionable event is when someone is being distracted, which is already notified. 

Maybe I missed the point?

2024-07-10 00:02 UTC, coupe-1 commented
It's probably a pretty narrow use case. The reason I want this is because I'll have my hand off my mouse while I'm texting or something, and the distraction will start, so I have to put my phone down, move my hand to my mouse then click the citizen and by then I've lost half the auto pickpockets. If I set this to 90, I get a notification typically like 3-5 seconds before it actually spawns so I can be ready to click. Idk how many other people will use this but I find it useful.

2024-07-10 00:35 UTC, sololegends commented
I suppose that makes sense.
I've made a few comments to conform to the normals of my coding style.

Additionally, any particular reason you removed the "Notify On"  clauses?

2024-07-10 00:35 UTC, sololegends requested changes

2024-07-10 00:35 UTC, sololegends commented on src/main/java/com/sololegends/runelite/VarlamoreHouseThievingPlugin.java
> +		long timeSinceLastDistraction = NextUpOverlayPanel.sinceDistraction();
Use snake case for variable names

2024-07-10 00:35 UTC, sololegends commented on src/main/java/com/sololegends/runelite/VarlamoreHouseThievingPlugin.java
> +		if (config.notifyOnTimeSinceDistraction() == timeSinceLastDistraction && config.notifyOnTimeSinceDistraction() > 0) {
Flow the second conditional, including operator, to the following line indented by on level. 
Otherwise the line length is too long.

2024-07-10 00:35 UTC, sololegends commented on src/main/java/com/sololegends/runelite/VarlamoreHouseThievingPlugin.java
> +			notify("It has been " + timeSinceLastDistraction + " seconds since the last distraction");
Should account for crazy people putting in 1 second and use the proper plurality.

2024-07-10 01:02 UTC, coupe-1 commented
I fixed what you requested. I think the "notify on" text is redundant considering that they're all in the notifications section. It's like adding "highlight" to the beginning of all the highlight options.

2024-07-10 01:12 UTC, sololegends commented
Fair enough. I'll merge this in next chance I get. 
Thanks for contributing ^.^

2024-07-10 01:31 UTC, coupe-1 commented
Cool thanks!

2024-07-22 16:32 UTC, sololegends approved these changes

2024-07-22 21:23 UTC, sololegends commented
Added in a squashed commit to preserve commits being signed. Thanks for the edit!  I added a thanks to you in the readme ^.^

/close

2024-07-22 21:24 UTC, closed without merging